language: node_js
#node_js:
#  - "iojs"

os:
  - linux
  - osx

env:
  global:
    - target: 0.28.2
    - PATH: ./node_modules/electron-updater-tools/bin:$PATH
    - PUBLISH_BINARY: false
    # Other available variables:
    # s3accessKeyId
    # s3secretAccessKey

before_install:
  # nvm is not yet supported on osx, manually install
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.25.4/install.sh | bash
  # native dependencies
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-4.8 g++-4.8 libelf-dev
  # x86 not supported on osx
  - if [[ $TRAVIS_OS_NAME != osx ]]; then sudo apt-get install -qq gcc-4.8.multilib g++-4.8-multilib; fi
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8
  # Only Publish when building a tag
  - if [[ $TRAVIS_BRANCH == `git describe --tags --always HEAD` ]]; then PUBLISH_BINARY=true; fi;
  # or if we put [publish binary] in the commit message
  - COMMIT_MESSAGE=$(git show -s --format=%B $TRAVIS_COMMIT | tr -d '\n')
  - if test "${COMMIT_MESSAGE#*'[publish binary]'}" != "$COMMIT_MESSAGE"; then PUBLISH_BINARY=true; fi;

install:
  - nvm install iojs
  # npm dependencies
  - npm install node-gyp -g
  - npm install electron-prebuilt@${target} -g
  - npm install

script:
  - elb configure --target ${target} release x64
  - if [[ $TRAVIS_OS_NAME != osx ]]; then elb configure --target ${target} release x86; fi

after_success:
  # pack the binaries for this platform
  - elpack --configuration release --arch x64
  - if [[ $TRAVIS_OS_NAME != osx ]]; then elpack --configuration release --arch x86; fi
  # publish to s3
  - if [[ $PUBLISH_BINARY == true ]]; then elpub -b evolve-bin -i $s3accessKeyId -k $s3secretAccessKey -C release -a x64; fi
  - if [[ $PUBLISH_BINARY == true ] && [ $TRAVIS_OS_NAME != osx ]]; then elpub -b evolve-bin -i $s3accessKeyId -k $s3secretAccessKey -C release -a x86; fi