os: Visual Studio 2015 CTP
platform: x64
version: "{build}"

environment:
  nodejs_version: "2.5.0"
  publish_binary: false
  bin_dir: ./node_modules/electron-updater-tools/bin

install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version $env:platform
  # install modules
  - npm install -g is-property # workaround until node 2.3.1
  - npm install -g node-gyp
  - npm install
  # Publish builds when tagged
  # Or if APPVEYOR_REPO_COMMIT_MESSAGE contains [publish binary]
  - ps: if($env:APPVEYOR_REPO_TAG) { $env:PUBLISH_BINARY = 'true' }
  - ps: if($env:APPVEYOR_REPO_COMMIT_MESSAGE.contains('[publish binary]')) { $env:PUBLISH_BINARY = 'true' }

test_script:
  - npm test

build_script:
  - bash %bin_dir%/elb configure x64 release
  - bash %bin_dir%/elb configure x64 debug
  - bash %bin_dir%/elb configure ia32 release
  - bash %bin_dir%/elb configure ia32 debug

after_build:
  - node %bin_dir%/elpack --arch x64 --configuration release 
  - node %bin_dir%/elpack --arch x64 --configuration debug
  - node %bin_dir%/elpack --arch ia32 --configuration release 
  - node %bin_dir%/elpack --arch ia32 --configuration debug

deploy_script:
  - if "%PUBLISH_BINARY%" == "true" ( node %bin_dir%/elpub -b evolve-bin -i %s3accessKeyId% -k %s3secretAccessKey% -a x64 -C release )
  - if "%PUBLISH_BINARY%" == "true" ( node %bin_dir%/elpub -b evolve-bin -i %s3accessKeyId% -k %s3secretAccessKey% -a x64 -C debug )
  - if "%PUBLISH_BINARY%" == "true" ( node %bin_dir%/elpub -b evolve-bin -i %s3accessKeyId% -k %s3secretAccessKey% -a ia32 -C release  )
  - if "%PUBLISH_BINARY%" == "true" ( node %bin_dir%/elpub -b evolve-bin -i %s3accessKeyId% -k %s3secretAccessKey% -a ia32 -C debug  )