os: Visual Studio 2015 CTP
platform: x64
version: "{build}"

environment:
  target: "0.28.2"
  nodejs_version: "2.2.1"
  publish_binary: false
  bin_dir: ./node_modules/electron-updater-tools/bin

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version $env:platform
  # install modules
  - npm install -g is-property # workaround until node 2.3.1
  - npm install -g node-gyp
  - npm install -g electron-prebuilt@%target%
  - npm install
  # Publish builds from tags
  - for /f "delims=" %%i in ('git describe --tags --always HEAD') do set HEAD=%%i
  - if "%APPVEYOR_REPO_BRANCH%" == "%HEAD%" ( set PUBLISH_BINARY=true )
  # Or if APPVEYOR_REPO_COMMIT_MESSAGE  contains [publish binary]
  - ps: if($env:APPVEYOR_REPO_COMMIT_MESSAGE.contains('[publish binary]')) { $env:PUBLISH_BINARY = 'true' } else { $env:PUBLISH_BINARY = 'false' }

test_script:
  - npm test

build_script:
  - bash %bin_dir%/elb --target %target% configure release x64
  - bash %bin_dir%/elb --target %target% configure release x86

after_build:
  - node %bin_dir%/elpack --configuration release --arch x64
  - node %bin_dir%/elpack --configuration release --arch x86

deploy_script:
  - if "%PUBLISH_BINARY%" == "true" ( node %bin_dir%/elpub -b evolve-bin -i %s3accessKeyId% -k %s3secretAccessKey% -C release -a x64 )
  - if "%PUBLISH_BINARY%" == "true" ( node %bin_dir%/elpub -b evolve-bin -i %s3accessKeyId% -k %s3secretAccessKey% -C release -a x86 )